//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public string CategoryID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
