//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string TicketID { get; set; }
        public string CustomerID { get; set; }
        public string ShowTimeID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string Statuss { get; set; }
        public Nullable<float> UnitPrice { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ShowTime ShowTime { get; set; }
    }
}
